### ISSUE TITLE
Brady/Tachcardia Output

### ISSUE THREAD

**Issue by injelee** [jl3392/bme590hrm#5]
It says on the assignment that we should indicate when brady- or tachcardia occurs in the ECG trace - does this mean compare certain threshold values for every instantaneous HR point and ouput a list of tachy/bradicardia/neither strings (e.g. [brady, tachy, tachy, brady, neither, neither...])?  Or should we output whether or not the patient has brady/tachycardia after averaging the whole data set of instantaneous heart rates and display just one output saying if the ECG trace shows that the patient has brady/tachcardia (e.g. ['This patient has bradycardia.']).

I feel like acquiring instantaneous brady/tachycardia points isn't very valuable information.

**Comment by jl3392** [comment]
Would like to ask Suyash for clarification.

**Comment by suyashkumar** [comment]
Hey team, good question! Good intuition regarding the relevance of instantaneous readings. 

Brady- and tachy- cardia are most clinically relevant over meaningful time intervals (particularly when looking retrospectively), so that's probably how you'd want to report your output (e.g. tachycardia from t=[0, 100] and t=[200, 300]) as opposed to instantaneously. 

@mlp6 can add more color here if needed!
